# Generated by Django 4.2.2 on 2023-06-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Сертификаты', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Области знаний', 'verbose_name_plural': 'Области знаний'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студенты', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='workexperiences',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
