# Generated by Django 4.2.2 on 2023-06-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_certificates_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.students'),
        ),
    ]
