# Generated by Django 4.2.2 on 2023-06-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_certificates_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(blank=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(max_length=255, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=255, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='students',
            name='projects',
            field=models.ManyToManyField(to='students.projects', verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='students',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.skills', verbose_name='Умения'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца работы'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='position_name',
            field=models.CharField(max_length=255, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.students', verbose_name='Студент'),
        ),
    ]
