# Generated by Django 4.2.2 on 2023-11-19 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_certificates_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Проекты', to=settings.AUTH_USER_MODEL),
        ),
    ]
