# Generated by Django 4.2.2 on 2024-06-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_pagevisit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageVisit",
        ),
    ]
